### ISSUE TITLE
unable to annotate

### ISSUE THREAD

**Issue by lchunleo** [2vin/yolo_annotation_tool#2]
hi
 when i input my video file which is mp4, i hit an issue, 

OpenCV Error: One of arguments' values is out of range (Bad trackbar maximal value) in icvCreateTrackbar

are you able to provide a toy video for testing on compatibility? thanks

**Comment by 2vin** [comment]
Please try this format, it should work:
./annotation -v video_path -l label_file -o output_folder

**Comment by jaideep11061982** [comment]
@2vin  can we use this tool for images
